#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right

modes:
  - attract
  - song_select
  - base
  - bumpers
  - rhythm
  - hurryup

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

smart_virtual:
  simulate_manual_plunger: true
  simulate_manual_plunger_timeout: 500ms

virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3
