#config_version=6

coils:
  c_flipper_left_main:
    number:
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
  c_flipper_right_hold:
    number:
    allow_enable: true
  c_trough_eject:
    number: