#config_version=6

mode:
  start_events: ball_starting{ball==1}
  stop_events: song_select_complete
  priority: 1500
  code: song_select.SongSelect

mode_settings:
  select_switch: s_action_button
  previous_switch: s_flipper_left
  next_switch: s_flipper_right
  music_root: sounds/music/Genres
  song_bus: music
  song_start_at: 0
